name: on push

on:
  push:
    branches:
     - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: |
         chmod +x ./hello.sh
         ./hello.sh
      shell: bash
